// AUTO-GENERATED by scripts/upload-media.mjs — do not edit by hand.
// Maps original /public media paths to their Firebase Storage download URLs.
export const HOSTED_MEDIA: Record<string, string> = {
  "/vid/bootom_video_just_above_footer.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvid%2Fbootom_video_just_above_footer.mp4?alt=media&token=8b9a9f60-541b-4aa3-b26a-26f181c15f25",
  "/videos/Orchha Testimotial 1.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FOrchha%20Testimotial%201.mp4?alt=media&token=428d9bfb-46c4-4645-8eba-daab127f9f10",
  "/videos/Orchha Testimonial 11.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FOrchha%20Testimonial%2011.mp4?alt=media&token=2ceb90f7-ea35-437b-97c6-8a6d8f26d3bd",
  "/videos/Orchha Testimonial 12.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FOrchha%20Testimonial%2012.mp4?alt=media&token=adeada8f-f9f4-4d5e-8718-c1636f10870b",
  "/videos/Orchha Testimonial 15.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FOrchha%20Testimonial%2015.mp4?alt=media&token=0e206117-9691-42c2-8c61-820bf3a10b63",
  "/videos/Orchha testimomnials 4.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FOrchha%20testimomnials%204.mp4?alt=media&token=2b39ff81-c4dd-4fff-b85c-7b4037cc9671",
  "/videos/Serior Citizen reel.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FSerior%20Citizen%20reel.mp4?alt=media&token=7df3657b-4811-4b47-b961-1cdb4cd3ea75",
  "/videos/Testimonial 7.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FTestimonial%207.mp4?alt=media&token=4b5d90eb-0e3d-4280-99fc-5770366d7e29",
  "/videos/Testimonial 8.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FTestimonial%208.mp4?alt=media&token=b124d9c7-965b-4106-b5e3-eeb6199d672e",
  "/videos/Testimonial Orchha Marathi 3.mp4": "https://firebasestorage.googleapis.com/v0/b/aankhon-dekha.firebasestorage.app/o/media%2Fvideos%2FTestimonial%20Orchha%20Marathi%203.mp4?alt=media&token=028576c3-7753-48c9-9f62-75b2c2fa32ee"
};
