/**
 * Upload the large videos referenced by the app to Firebase Storage and
 * generate src/lib/media.generated.ts mapping each /public path to a public
 * download URL.
 *
 * Uses the Admin SDK + service-account key (git-ignored). Each object gets a
 * Firebase download token, so the resulting URL works without Storage rules
 * changes. Re-running re-uploads and refreshes the map.
 *
 * Run:  node scripts/upload-media.mjs
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { initializeApp, cert } from "firebase-admin/app";
import { getStorage } from "firebase-admin/storage";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const BUCKET = "aankhon-dekha.firebasestorage.app";

// Only the media actually referenced in the UI (paths are /public-relative).
const FILES = [
  "/vid/bootom_video_just_above_footer.mp4",
  "/videos/Orchha Testimotial 1.mp4",
  "/videos/Orchha Testimonial 11.mp4",
  "/videos/Orchha Testimonial 12.mp4",
  "/videos/Orchha Testimonial 15.mp4",
  "/videos/Orchha testimomnials 4.mp4",
  "/videos/Serior Citizen reel.mp4",
  "/videos/Testimonial 7.mp4",
  "/videos/Testimonial 8.mp4",
  "/videos/Testimonial Orchha Marathi 3.mp4",
];

function findServiceAccount() {
  if (process.env.SERVICE_ACCOUNT) return process.env.SERVICE_ACCOUNT;
  const hit = readdirSync(root).find((f) => /firebase-adminsdk.*\.json$/.test(f));
  if (!hit) throw new Error("Service account key not found in project root.");
  return join(root, hit);
}

const serviceAccount = JSON.parse(readFileSync(findServiceAccount(), "utf8"));
initializeApp({ credential: cert(serviceAccount), storageBucket: BUCKET });
const bucket = getStorage().bucket();

function downloadUrl(destPath, token) {
  return `https://firebasestorage.googleapis.com/v0/b/${BUCKET}/o/${encodeURIComponent(
    destPath,
  )}?alt=media&token=${token}`;
}

/** Token of an already-uploaded object, or null. */
async function existingToken(file) {
  try {
    const [exists] = await file.exists();
    if (!exists) return null;
    const [meta] = await file.getMetadata();
    const tok = meta?.metadata?.firebaseStorageDownloadTokens;
    return tok ? String(tok).split(",")[0] : null;
  } catch {
    return null;
  }
}

async function main() {
  const map = {};
  const failed = [];

  for (const publicPath of FILES) {
    const local = join(root, "public", publicPath.replace(/^\//, ""));
    if (!existsSync(local)) {
      console.warn(`! skip (missing locally): ${publicPath}`);
      continue;
    }
    const destPath = `media${publicPath}`; // e.g. media/videos/Testimonial 7.mp4
    const file = bucket.file(destPath);

    // Already uploaded? reuse it (idempotent / resumable across runs).
    const existing = await existingToken(file);
    if (existing) {
      map[publicPath] = downloadUrl(destPath, existing);
      console.log(`= already uploaded: ${publicPath}`);
      continue;
    }

    const token = randomUUID();
    process.stdout.write(`↑ ${publicPath} … `);
    try {
      await bucket.upload(local, {
        destination: destPath,
        resumable: true,
        metadata: {
          contentType: "video/mp4",
          cacheControl: "public, max-age=31536000",
          metadata: { firebaseStorageDownloadTokens: token },
        },
      });
      map[publicPath] = downloadUrl(destPath, token);
      console.log("done");
    } catch (err) {
      console.log("FAILED");
      console.warn(`  ${err?.message?.slice(0, 120) || err}`);
      failed.push(publicPath);
    }
  }

  const out =
    "// AUTO-GENERATED by scripts/upload-media.mjs — do not edit by hand.\n" +
    "// Maps original /public media paths to their Firebase Storage download URLs.\n" +
    "export const HOSTED_MEDIA: Record<string, string> = " +
    JSON.stringify(map, null, 2) +
    ";\n";
  writeFileSync(join(root, "src", "lib", "media.generated.ts"), out);
  console.log(`\n✓ wrote src/lib/media.generated.ts (${Object.keys(map).length} entries)`);
  if (failed.length) {
    console.log(`\n${failed.length} failed — re-run to resume:`);
    failed.forEach((f) => console.log(`  ${f}`));
    process.exit(2);
  }
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
